
name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: curl -O https://raw.githubusercontent.com/cc332030/linux/master/script/init-ssh-pre.sh && sudo sh init-ssh-pre.sh
      - run: curl -O https://raw.githubusercontent.com/cc332030/linux/master/script/init-ssh.sh && sh init-ssh.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: whoami && pwd
      - run: ls -alh ~
      - run: ls -alh ~/.ssh
      - run: ssh -T git@github.com
