
name: publish

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: curl -o init-ssh.sh  https://raw.githubusercontent.com/cc332030/linux/master/script/init-ssh.sh && sh -c "init-ssh.sh "
      - run: ls -alh ~
      - run: ls -alh ~/.ssh
      - run: ssh -T git@github.com
